spring.application.name=Job Exchange

server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.url=jdbc:mysql://localhost:3306/job_exchange

spring.datasource.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.freemarker.suffix=.ftl

spring.freemarker.template-exception-handler=rethrow
spring.freemarker.log-template-exceptions=false
spring.freemarker.cache=false


